name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  merge_group:

permissions:
  contents: read
  packages: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install protoc
      run: script/install-protoc
    - name: Build
      run: make build
    - name: Run tests
      run: make test

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install protoc
      run: script/install-protoc
    - name: Lint
      run: make lint
