# This workflow only publishes releases for PR's created by create-release-pr.yml
#
# See https://github.com/github/twirp-rs/blob/main/CONTRIBUTING.md#releasing for more details.
name: Release any unpublished twirp/twirp-build packages

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  # Release any unpublished packages
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
