# This workflow only publishes releases for PR's created by create-release-pr.yml
#
# See https://github.com/github/twirp-rs/blob/main/CONTRIBUTING.md#releasing for more details.
name: Release any unpublished twirp/twirp-build packages

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  # Release any unpublished packages
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
      - name: Run release-plz
        uses: release-plz/action@a80d79efe0a195618acb02a4089d55fe74d2505f # v0.5.136
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
